#!/usr/bin/env python3
"""
build_curated.py — emit charts-curated.js: the iReal changes for just the CURATED tunes,
small enough to load synchronously at boot so the app's iReal overlay applies correct changes
to the curated TUNES without pulling the full 2.5MB charts-ireal.js. Regenerate after re-importing.
"""
import json, re

html = open('index.html', encoding='utf-8').read()
# tune entries have id + title + composer
titles = re.findall(r"id:'([^']+)',title:'((?:[^'\\]|\\.)*)',composer:", html)
curated = []
for _id, t in titles:
    curated.append(t.replace("\\'", "'"))

s = open('charts/charts-ireal.js', encoding='utf-8').read()
arr = json.loads(s[s.index('concat(')+7:s.rindex(')')])
norm = lambda x: re.sub(r'[^a-z0-9]', '', (x or '').lower())
by = {}
for c in arr:
    if c.get('bars'):
        by.setdefault(norm(c['title']), c)

out, seen = [], set()
for t in curated:
    n = norm(t)
    c = by.get(n)
    if c and n not in seen:
        out.append({'title': c['title'], 'key': c.get('key', ''), 'bars': c['bars']})
        seen.add(n)
    elif not c:
        print('  (no iReal match for curated tune: '+t+')')

js = ("/* charts-curated.js — iReal changes for the curated tunes only (subset of charts-ireal.js),\n"
      "   loaded at boot so the overlay corrects the curated TUNES' changes without the full import.\n"
      "   Generated by build_curated.py — regenerate when charts-ireal.js changes. */\n"
      "window.USER_CHARTS=(window.USER_CHARTS||[]).concat(" + json.dumps(out, ensure_ascii=False) + ");\n")
open('charts/charts-curated.js', 'w', encoding='utf-8').write(js)
print('wrote', len(out), 'curated charts to charts-curated.js')
